[SuperMini_nRF_HT_RA62]
extends = nrf52_base
board = promicro_nrf52840
build_flags = ${nrf52_base.build_flags}
  -I variants/supermini_nrf_ht_ra62
  -D PROMICRO
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D LORA_TX_POWER=22
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=1
  -D SX126X_DIO2_AS_RF_SWITCH=1
  -D SX126X_DIO3_TCXO_VOLTAGE=1.8
  -D PIN_BOARD_SCL=7
  -D PIN_BOARD_SDA=8
  -D PIN_OLED_RESET=-1
  -D PIN_USER_BTN=6
  -D DISPLAY_CLASS=NullDisplayDriver
build_src_filter = ${nrf52_base.build_src_filter}
  +<helpers/sensors>
  +<../variants/supermini_nrf_ht_ra62>
  +<helpers/ui/NullDisplayDriver.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../variants/supermini_nrf_ht_ra62/DS18B20Sensor.cpp>
lib_deps = ${nrf52_base.lib_deps}
  paulstoffregen/OneWire @ ^2.3.8
  milesburton/DallasTemperature @ ^3.11.0

[env:SuperMini_nRF_HT_RA62_repeater]
extends = SuperMini_nRF_HT_RA62
build_src_filter = ${SuperMini_nRF_HT_RA62.build_src_filter}
  +<../examples/simple_repeater>
build_flags =
  ${SuperMini_nRF_HT_RA62.build_flags}
  -D ADVERT_NAME='"SuperMini nRF HT-RA62"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50

[env:SuperMini_nRF_HT_RA62_companion_radio_usb]
extends = SuperMini_nRF_HT_RA62
board_build.ldscript = boards/nrf52840_s140_v6_extrafs.ld
board_upload.maximum_size = 712704
build_flags = ${SuperMini_nRF_HT_RA62.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
build_src_filter = ${SuperMini_nRF_HT_RA62.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps = ${SuperMini_nRF_HT_RA62.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:SuperMini_nRF_HT_RA62_companion_radio_ble]
extends = SuperMini_nRF_HT_RA62
board_build.ldscript = boards/nrf52840_s140_v6_extrafs.ld
board_upload.maximum_size = 712704
build_flags = ${SuperMini_nRF_HT_RA62.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D OFFLINE_QUEUE_SIZE=256
build_src_filter = ${SuperMini_nRF_HT_RA62.build_src_filter}
  +<helpers/nrf52/SerialBLEInterface.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps = ${SuperMini_nRF_HT_RA62.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:SuperMini_nRF_HT_RA62_room_server]
extends = SuperMini_nRF_HT_RA62
build_src_filter = ${SuperMini_nRF_HT_RA62.build_src_filter}
  +<../examples/simple_room_server>
build_flags = ${SuperMini_nRF_HT_RA62.build_flags}
  -D ADVERT_NAME='"SuperMini nRF HT-RA62 Room"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'

[env:SuperMini_nRF_HT_RA62_kiss_modem]
extends = SuperMini_nRF_HT_RA62
build_src_filter = ${SuperMini_nRF_HT_RA62.build_src_filter}
  +<../examples/kiss_modem/>